@startuml

'https://plantuml.com/sequence-diagram

skinparam shadowing false
skinparam defaultFontName xfonts-wqy
skinparam dpi 300
skinparam activity  {
    DiamondFontSize 14
    ArrowFontSize 14
    FontSize 14
}
autonumber

actor 连接者 as Client
participant 外围系统 as Server
participant Connect服务节点 as Connect
participant 连接管理 as ServerConnContainer
participant 连接验证 as ConnAuthHandler
participant Auth服务 as AuthServer
participant 路由信息管理 as RouteAddressManager
database Redis

activate Client
Client -> Server ++: 创建连接
Server -> Connect ++: 创建连接
Connect -> ConnAuthHandler ++: 连接验证
ConnAuthHandler -> AuthServer ++: 验证Token
return 验证结果
return 验证结果，假设验证通过
Connect -> ServerConnContainer ++: 添加连接
ServerConnContainer -> ServerConnContainer++--: 保存连接
ServerConnContainer -> RouteAddressManager++: 如果是新连接者则保存路由信息
RouteAddressManager -> Redis ++: 保存路由信息
return ok
return ok
return ok
return ok

@enduml