@startuml
'https://plantuml.com/class-diagram
skinparam shadowing false
skinparam defaultFontName xfonts-wqy
skinparam dpi 300
skinparam activity  {
    DiamondFontSize 14
    ArrowFontSize 14
    FontSize 14
}

package application {
    class ServerAuthenticationAppService {
        - ServerInfoService serverInfoService
        - TokenCredentialService tokenCredentialService
        - ServerCredentialAuthConfig serverCredentialAuthConfig
        - ServerTokenCredential createServerCredential(ServerAuthCommand)
        - ServerTokenCredential verifyAndGetToken(String token)
    }
    class ServerAppService {
        - ServerInfoService serverInfoService
        - Long register(String serverName, String secret)
    }
}

package domain {
    class TokenCredentialService<T extends TokenCredential> {
        - ITokenHandler tokenHandler
        + completeAndSave(TokenCredential, TokenCredentialSpec)
        + T verifyAndGet(String token, Class<T> credentialType)
        + T verifyAndInvalidateToken(String token, Class<T> credentialType)
        + T invalidateToken(String token, Class<T> credentialType)
    }
    class ServerInfoService {
        - PasswordEncoder passwordEncoder
        - ServerInfoRepository serverInfoRepository
        - ServerDigestValidator serverDigestValidator
        - ServerInfoEntity verifyAndGetInfo(String serverName, String secret)
        - Long createAuthInfo(String serverName, String secret)
    }
    interface ServerInfoRepository {
        + ServerInfo findById(Long id)
        + void insert(ServerInfoEntity)
    }
    class ServerDigestValidator {
        - ServerDigestGenerator serverDigestGenerator
        + boolean validate(String userInput, ServerInfoEntity)
    }

    class ServerDigestGenerator {
        - MessageDigest messageDigest
        + byte[] generate(Long serverId, String serverName, String secret)
    }
}
ServerAuthenticationAppService ..> TokenCredentialService: Token生成与Token校验
ServerAppService .> ServerInfoService: 注册服务
ServerAuthenticationAppService .> ServerInfoService: 验证服务

ServerInfoService ..> ServerInfoRepository: 数据库操作
ServerInfoService ..> ServerDigestValidator: 摘要验证
ServerDigestValidator ..> ServerDigestGenerator: 摘要生成


@enduml