@startuml
'https://plantuml.com/class-diagram

class NettyServer {

}
class NettyClient
class NettyServerBootstrap
class ServerConnManager
class AppConnManager
class UserSessionManager
class MsgConnection
@enduml