@startuml
'https://plantuml.com/class-diagram

namespace adapter {
    class UserController {
        - UserService userService
        + Result<UserLoginResponse> login(UserLoginRequest)
    }
}

adapter --> client: 返回值类型

namespace client {
    namespace client.service {
        interface UserService {
            + Result<UserLoginResponse> login(UserLoginRequest)
        }
    }
    namespace client.dto {
        namespace client.dto.request {
            class UserLoginRequest
        }
        namespace client.dto.response {
            class UserLoginResponse
        }
        namespace client.dto.criteria {
             class UserCriteria
        }
    }
}

namespace app {
    namespace app.service {
        class UserServiceImpl implements client.service.UserService {
            + Result<UserLoginResponse> login(UserLoginRequest)
        }
    }
}

client.service --> client.dto: DTO依赖

namespace infrastructure {
    namespace infrastructure.adapter {
        namespace infrastructure.adapter.database {
            interface UserAdapter {
                - UserMapper userMapper;
            }
            namespace infrastructure.adapter.database.mapper {
                interface UserMapper
            }
        }
    }
    namespace infrastructure.converter {
        interface UserConverter {
            + User toUser(UserLoginRequest req)
        }
    }
    namespace infrastructure.gateway {
        class UserGatewayImpl {
            - UserConverter converter;
            - UserAdapter adapter;
            + {static} User init(Long userId)
            + {static} User login()
            + {static} UserLoginResponse toUserLoginResponse()
        }
    }
}
infrastructure.gateway.UserGatewayImpl -up-> infrastructure.converter.UserConverter: 类型转换
infrastructure.gateway.UserGatewayImpl -up-> infrastructure.adapter.database.UserAdapter: 操作数据库
infrastructure.adapter.database.UserAdapter -> infrastructure.adapter.database.mapper.UserMapper: 操作数据库

namespace domain {
    namespace domain.user {
        class User {
            - Long userId;
            - String username;
            - String pwd;
            ---
            - {static} UserGateway gateway
            + {static} User init(Long userId)
            + {static} User login()
            + {static} UserLoginResponse toUserLoginResponse()
        }
        namespace domain.gateway {
            interface UserGateway {
                + User init(Long userId)
                + User login()
                + UserLoginResponse toUserLoginResponse()
            }
        }
    }
}
domain.user.User -> domain.gateway.UserGateway: 网关路由

app.service.UserServiceImpl -down-> domain.user.User: 通过聚合根的静态方法进行转换、处理、响应

infrastructure.gateway.UserGatewayImpl -down-|> domain.gateway.UserGateway: 实现

@enduml