@startuml
'https://plantuml.com/class-diagram

abstract class AbstractMsg {
    # Long msgId
    # MsgType msgType
    # String msgTopic
    # Boolean resend
    # Date sendTime
    # boolean persistentMsg
    + boolean isPersistentMsg()
}

abstract class PersistentMsg extends AbstractMsg {
    persistentMsg = true
    ---
    # Integer transferStatus // revd/sent/read
    # Date saveTime
    # Date recvTime
}

abstract class ContentMsg extends PersistentMsg {
    # Serializable senderId
    # Long senderAppId
    # Object/byte[] data
}

class PersonalMsg extends ContentMsg {
    msgType=Personal
    ---
    # Long revrAppId
    # Serializable revrId
    # boolean hasRead
}

note left of PersonalMsg: 有多个接收方时，\n每个接收方单独发送一个PersonalMsg

class GroupMsg extends ContentMsg {
    msgType=Group
    ---
    # Long groupAppId
    # Long groupId
}

class AckMsg {
    # Long msgId
    # Msg msgType=Ack
    # Long ackMsgId
    # Long revrAppId
    # Serializable revrId
    # Integer ackType // revd/sent/read
}

note right of AckMsg#ackType: 用于修改消息状态

class NotificationMsg extends AbstractMsg {
    msgType = Notification
    persistentMsg = false
    ---
    # Long revrAppId
    # Serializable revrId
    # Object/byte[] data
}
note bottom of NotificationMsg: 发送方为系统

class EventMsg extends AbstractMsg {
    msgType = Event
    persistentMsg = false
    ---
    # Object data
}

enum MsgType {
    PersonalMsg
    GroupMsg
    Ack
    System
}
