@startuml
'https://plantuml.com/sequence-diagram

skinparam shadowing false
skinparam defaultFontName xfonts-wqy
skinparam dpi 300
skinparam activity  {
    DiamondFontSize 14
    ArrowFontSize 14
    FontSize 14
}
autonumber

participant Token验证器 as ICreentialVerifier
participant Token验证结果缓存 as ServerCredentialCacheHandler
participant Auth服务 as Auth
database Redis

activate ICreentialVerifier
ICreentialVerifier -> ServerCredentialCacheHandler ++: 验证token
ServerCredentialCacheHandler -> Redis ++:查缓存
return 缓存结果

alt 缓存不存在
    ServerCredentialCacheHandler -> Auth++: 验证token
    return 验证结果，如果通过校验，则返回 TokenCredential
    ServerCredentialCacheHandler -> Redis++:缓存验证结果
    return ok
else 缓存存在
    ICreentialVerifier <- ServerCredentialCacheHandler: 跳过远程调用，直接返回验证结果
end

ServerCredentialCacheHandler -> ServerCredentialCacheHandler ++--: 验证缓存
alt 验证通过
    ICreentialVerifier <- ServerCredentialCacheHandler: 返回缓存的 TokenCredential
else 验证不通过
    ICreentialVerifier <- ServerCredentialCacheHandler--: 返回缓存null
end

@enduml