@startuml
'https://plantuml.com/class-diagram
skinparam shadowing false
skinparam defaultFontName xfonts-wqy
skinparam dpi 300
skinparam activity  {
    DiamondFontSize 14
    ArrowFontSize 14
    FontSize 14
}

class MsgAcceptor {
    - MqProducer mqProducer;
    - MsgMqTopic msgMqTopic;
    + Result<Long> sendMsg(Msg msg, MsgHeader msgHeader)
}

MsgAcceptor .> MqProducer: 消息关系验证


class MqProducer {
    - KafkaTemplate<Long, Msg> kafkaTemplate;
    + SendResult<Long, Msg> send(String topic, Long key, Msg msg)
}

@enduml