@startuml
'https://plantuml.com/class-diagram

class ServerConnManager {
    - Map<Long, Connector> connectors;
    + void addConn(Long connectorId, Connector)
    + void removeConn(Long connectorId, connId)
    + Connection getConn(Long connectorId, UUID connId)
    + Map<UUID, Connection> getConns(Long connectorId)
    + boolean containsConn(Connector)
}

class Connector {
    - Long appId;
    - Serializable connectorId;
    - Map<connId, Connection> conns;
}

class Connection {
    - UUID connId;
    - ChannelHandlerContext ctx;
    - Serializable connectorId;
}

ServerConnManager o-- Connector
Connector o- Connection

@enduml